// Dish Category - Type of dish based on Rangeela Dhaba menu
export enum DishCategory {
  HAKKA_NOODLES = 'Hakka Noodles',
  VEG_STARTERS = 'Veg Starters',
  NON_VEG_STARTERS = 'Non Veg Starters',
  SALAD_RAITA = 'Salad & Raita',
  CHINESE_VEG = 'Chinese Veg',
  CHINESE_NON_VEG = 'Chinese Non Veg',
  BIRYANI = 'Biryani',
  FRIED_RICE_PULAO = 'Fried Rice & Pulao',
  VEG_MAIN_COURSE = 'Veg Main Course',
  NON_VEG_MAIN_COURSE = 'Non Veg Main Course',
  MUGHLAI = 'Mughlai',
  ROTI_PARATHA = 'Roti & Paratha',
  TANDOORI = 'Tandoori',
  TADKA = 'Tadka',
  DESSERTS_BEVERAGES = 'Desserts & Beverages',
  DOSA = 'Dosa',
  IDLI_VADA = 'Idli Vada',
  UTTAPAM = 'Uttapam',
  JUICE = 'Juice',
}
